<?php
/**
 * Created by PhpStorm.
 * User: mfrancis
 * Date: 2018-09-03
 * Time: 04:44
 */

namespace App\Columns;

class ClePlanner
{
    public function getColumns()
    {
        return [
            'khz' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'khz',
                'highlight' =>  false,
                'label'     =>  'KHz',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Nominal Carrier',
            ],
            'call' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'call',
                'highlight' =>  'call',
                'label'     =>  'ID',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Callsign or other ID',
            ],
            'type' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'type',
                'highlight' =>  false,
                'label'     =>  'Type',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'hidden',
                'th_class'  =>  'hidden',
                'tooltip'   =>  '',
            ],
            'QTH' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'QTH',
                'highlight' =>  false,
                'label'     =>  '\'Name\' and Location',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
            'SP' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'SP',
                'highlight' =>  'states',
                'label'     =>  'S/P',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'State / Province / Territory',
            ],
            'ITU' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'ITU',
                'highlight' =>  'countries',
                'label'     =>  'ITU',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Country',
            ],
            'region' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'region',
                'highlight' =>  'region',
                'label'     =>  'Region',
                'labelSort' =>  'Region',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'caps',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Continent or Zone',
            ],
            'GSQ' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'GSQ',
                'highlight' =>  'gsq',
                'label'     =>  'GSQ',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'txt_r monospace',
                'th_class'  =>  '',
                'tooltip'   =>  'Signal Grid Square',
            ],

            'notes' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'notes',
                'highlight' =>  false,
                'label'     =>  'Notes',
                'labelSort' =>  'Notes',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'l2',
                'th_class'  =>  'l2',
                'tooltip'   =>  'Notes about this signal',
            ],
            'heard_in' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'heard_in_html',
                'highlight' =>  'heard_in',
                'label'     =>  'Heard In<br /><b>(Daytime Log)</b>',
                'labelSort' =>  'Heard In',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'l2',
                'th_class'  =>  'l2',
                'tooltip'   =>  'Places signal has been reported',
            ],
            'first_heard' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'first_heard',
                'highlight' =>  false,
                'label'     =>  'First Logged',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'text-nowrap txt_r monospace',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
            'last_heard' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'last_heard',
                'highlight' =>  false,
                'label'     =>  'Last Logged',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'text-nowrap txt_r monospace',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
            'AF' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'AF',
                'highlight' =>  '',
                'label'     =>  'AF',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'cle_planner_stats',
                'th_class'  =>  '',
                'tooltip'   =>  'Logs in Africa',
            ],
            'AN' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'AN',
                'highlight' =>  '',
                'label'     =>  'AN',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'cle_planner_stats',
                'th_class'  =>  '',
                'tooltip'   =>  'Logs in Antarctica',
            ],
            'AS' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'AS',
                'highlight' =>  '',
                'label'     =>  'AS',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'cle_planner_stats',
                'th_class'  =>  '',
                'tooltip'   =>  'Logs in Asia',
            ],
            'CA' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'CA',
                'highlight' =>  '',
                'label'     =>  'CA',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'cle_planner_stats',
                'th_class'  =>  '',
                'tooltip'   =>  'Logs in Caribbean',
            ],
            'EU' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'EU',
                'highlight' =>  '',
                'label'     =>  'EU',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'cle_planner_stats',
                'th_class'  =>  '',
                'tooltip'   =>  'Logs in Europe',
            ],
            'IW' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'IW',
                'highlight' =>  '',
                'label'     =>  'IW',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'cle_planner_stats',
                'th_class'  =>  '',
                'tooltip'   =>  'Logs in International Waters',
            ],
            'NA' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'NA',
                'highlight' =>  '',
                'label'     =>  'NA',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'cle_planner_stats',
                'th_class'  =>  '',
                'tooltip'   =>  'Logs in North America',
            ],
            'OC' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'OC',
                'highlight' =>  '',
                'label'     =>  'OC',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'cle_planner_stats',
                'th_class'  =>  '',
                'tooltip'   =>  'Logs in Oceania',
            ],
            'SA' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'SA',
                'highlight' =>  '',
                'label'     =>  'SA',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'cle_planner_stats',
                'th_class'  =>  '',
                'tooltip'   =>  'Logs in South America',
            ],
        ];
    }
}
