<?php
namespace App\Columns;

class Donations
{
    public function getColumns()
    {
        return [
            'id' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'id',
                'highlight' =>  'id',
                'label'     =>  'ID',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'id',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Donor Name',
            ],
            'date' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'date',
                'highlight' =>  'date',
                'label'     =>  'Date',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'date',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Donation Date',
            ],
            'amount' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'amount',
                'highlight' =>  'amount',
                'label'     =>  'Amount',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'amount',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Amount of Donation',
            ],
            'name' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'name',
                'highlight' =>  'name',
                'label'     =>  'Name',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'donor.name',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Donor Name',
            ],
            'display' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'display',
                'highlight' =>  'display',
                'label'     =>  'Display Name',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'display',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Donor Display Name',
            ],
            'anonymous' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'anonymous',
                'highlight' =>  'anonymous',
                'label'     =>  'Anon',
                'labelSort' =>  '',
                'order'     =>  'd',
                'sort'      =>  'anonymous',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Donor details hidden',
            ],
            'callsign' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'callsign',
                'highlight' =>  'callsign',
                'label'     =>  'Callsign',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'display',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Donor Callsign',
            ],
            'sp' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'sp',
                'highlight' =>  'sp',
                'label'     =>  'S/P',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'sp',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Donor S/P',
            ],
            'itu' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'itu',
                'highlight' =>  'itu',
                'label'     =>  'ITU',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'itu',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Donor ITU',
            ],
            'notes' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'notes',
                'highlight' =>  'notes',
                'label'     =>  'Notes',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'notes',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Donor Notes',
            ],
            'message' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'message',
                'highlight' =>  'message',
                'label'     =>  'Message',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'message',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Message with Donation',
            ],
      ];
    }
}