<?php
namespace App\Columns;

class Donors
{
    public function getColumns()
    {
        return [
            'name' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'name',
                'highlight' =>  'name',
                'label'     =>  'Name',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'name',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Name of Donor',
            ],
            'display' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'display',
                'highlight' =>  'display',
                'label'     =>  'Display Name',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'display',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Display Name for Donor',
            ],
            'callsign' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'callsign',
                'highlight' =>  'callsign',
                'label'     =>  'Callsign',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'callsign',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Callsign for Donor',
            ],
            'email' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'email',
                'highlight' =>  'email',
                'label'     =>  'Email',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'email',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Email address for donor (not shown)',
            ],
            'itu' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'itu',
                'highlight' =>  'itu',
                'label'     =>  'ITU',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'itu',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Donor\'s Country',
            ],
            'sp' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'sp',
                'highlight' =>  'sp',
                'label'     =>  'SP',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'sp',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Donor\s State or Province',
            ],
            'notes' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'notes',
                'highlight' =>  'notes',
                'label'     =>  'Notes',
                'labelSort' =>  '',
                'order'     =>  'a',
                'sort'      =>  'notes',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'rowspan2',
                'tooltip'   =>  'Note about donor',
            ],
            'anonymous' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'anonymous',
                'highlight' =>  false,
                'label'     =>  'Anon',
                'labelSort' =>  '',
                'order'     =>  'd',
                'sort'      =>  'anonymous',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Whether donor requests to be anonymous',
            ],
            'donations' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'donations',
                'highlight' =>  'donations',
                'label'     =>  'Num',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Number of Donations',
            ],
            'total' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'total',
                'highlight' =>  'total',
                'label'     =>  'Total',
                'labelSort' =>  '',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  'rowspan2',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Sum of Donations',
            ],
        ];
    }
}