<?php
/**
 * Created by PhpStorm.
 * User: mfrancis
 * Date: 2018-09-03
 * Time: 04:44
 */

namespace App\Columns;

class Logsessions
{
    public function getColumns()
    {
        return [
            'id' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'id',
                'label'     =>  'Session ID',
                'order'     =>  'a',
                'sort'      =>  'ls.id',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
            'timestamp' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'timestamp',
                'label'     =>  'Uploaded Date',
                'order'     =>  'd',
                'sort'      =>  'ls.timestamp',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
            'uploader' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'uploader',
                'label'     =>  'Uploaded By',
                'order'     =>  'a',
                'sort'      =>  'u.name',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
            'comment' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'comment',
                'label'     =>  'Comment',
                'order'     =>  'a',
                'sort'      =>  'ls.comment',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
            'listener' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'listener',
                'label'     =>  'Listener | Location',
                'order'     =>  'a',
                'sort'      =>  'li.name',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
            'operator' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'operator',
                'label'     =>  'Operator<br>(if remote)',
                'order'     =>  'a',
                'sort'      =>  'op.name',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'For multi-operator locations',
            ],
            'callsign' => [
                'admin' =>      false,
                'arg' =>        '',
                'field' =>      'callsign',
                'highlight' =>  'q',
                'label' =>      'Callsign',
                'order' =>      'a',
                'sort' =>       'li.callsign',
                'td_class' =>   'l2',
                'th_class' =>   'l2',
                'tooltip' =>    'Ham Radio Callsign',
            ],
            'qth' => [
                'admin' =>      false,
                'arg' =>        '',
                'field' =>      'qth',
                'highlight' =>  'q',
                'label' =>      'QTH',
                'order' =>      'a',
                'sort' =>       'li.qth',
                'td_class' =>   '',
                'th_class' =>   '',
                'tooltip' =>    'Location',
            ],
            'sp' => [
                'admin' =>      false,
                'arg' =>        '',
                'field' =>      'sp',
                'highlight' =>  false,
                'label' =>      'S/P',
                'order' =>      'a',
                'sort' =>       'li.sp',
                'td_class' =>   '',
                'th_class' =>   '',
                'tooltip' =>    'State / Province / Territory',
            ],
            'itu' => [
                'admin' =>      false,
                'arg' =>        '',
                'field' =>      'itu',
                'highlight' =>  'country',
                'label' =>      'ITU',
                'order' =>      'a',
                'sort' =>       'li.itu',
                'td_class' =>   '',
                'th_class' =>   '',
                'tooltip' =>    'Country',
            ],
            'signals' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'signals',
                'label'     =>  'Signals',
                'order'     =>  'd',
                'sort'      =>  'ls.signals',
                'td_class'  =>  'txt_r',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Total number of signals received',
            ],
            'logs' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'logs',
                'label'     =>  'Logs',
                'order'     =>  'd',
                'sort'      =>  'ls.logs',
                'td_class'  =>  'txt_r',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Total number of logs for all signals',
            ],
            'logsDgps' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'logsDgps',
                'label'     =>  'DGPS',
                'order'     =>  'd',
                'sort'      =>  'ls.logsDgps',
                'td_class'  =>  'txt_r type_dgps',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Number of DGPS logs processed',
            ],
            'logsDsc' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'logsDsc',
                'label'     =>  'DSC',
                'order'     =>  'd',
                'sort'      =>  'ls.logsDsc',
                'td_class'  =>  'txt_r type_dsc',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Number of DSC logs processed',
            ],
            'logsHambcn' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'logsHambcn',
                'label'     =>  'HAMBCN',
                'order'     =>  'd',
                'sort'      =>  'ls.logsHambcn',
                'td_class'  =>  'txt_r type_hambcn',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Number of Ham Beacon logs processed',
            ],
            'logsNavtex' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'logsNavtex',
                'label'     =>  'Navtex',
                'order'     =>  'd',
                'sort'      =>  'ls.logsNavtex',
                'td_class'  =>  'txt_r type_navtex',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Number of NAVTEX station logs processed',
            ],
            'logsNdb' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'logsNdb',
                'label'     =>  'NDB',
                'order'     =>  'd',
                'sort'      =>  'ls.logsNdb',
                'td_class'  =>  'txt_r type_ndb',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Number of NDB logs processed',
            ],
            'logsTime' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'logsTime',
                'label'     =>  'Time',
                'order'     =>  'd',
                'sort'      =>  'ls.logsTime',
                'td_class'  =>  'txt_r type_time',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Number of Time station logs processed',
            ],
            'logsOther' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'logsOther',
                'label'     =>  'Other',
                'order'     =>  'd',
                'sort'      =>  'ls.logsOther',
                'td_class'  =>  'txt_r type_other',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  'Number of other station logs processed',
            ],
            'firstLog' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'firstLog',
                'label'     =>  'First Log date',
                'order'     =>  'd',
                'sort'      =>  'ls.firstLog',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
            'lastLog' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'lastLog',
                'label'     =>  'Last Log Date',
                'order'     =>  'd',
                'sort'      =>  'ls.lastLog',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
            'map' => [
                'admin' =>      false,
                'arg' =>        '',
                'field' =>      'getSignalsMap',
                'highlight' =>  false,
                'label' =>      'Map',
                'order' =>      '',
                'sort' =>       '',
                'td_class' =>   '',
                'th_class' =>   '',
                'tooltip' =>    'Map showing Signals for Log Session',
            ],
            'uploadStatus' => [
                'admin'     =>  true,
                'arg'       =>  '',
                'field'     =>  'uploadStatus',
                'label'     =>  'Status',
                'order'     =>  'a',
                'sort'      =>  'ls.uploadStatus',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
            'uploadPercent' => [
                'admin'     =>  true,
                'arg'       =>  '',
                'field'     =>  'uploadPercent',
                'label'     =>  '%',
                'order'     =>  'a',
                'sort'      =>  'ls.uploadPercent',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
            'delete' => [
                'admin'     =>  true,
                'arg'       =>  '',
                'field'     =>  'delete',
                'label'     =>  'Delete',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  '',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  '',
            ],
        ];
    }
}
