<?php
/**
 * Created by PhpStorm.
 * User: mfrancis
 * Date: 2018-09-03
 * Time: 04:44
 */

namespace App\Columns;

class Signals
{
    public function getColumns()
    {
        return [
            'khz' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'khz',
                'label'     =>  'KHz',
                'order'     =>  'a',
                'sort'      =>  's.khz',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Frequency',
            ],
            'call' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'call',
                'label'     =>  'ID',
                'order'     =>  'a',
                'sort'      =>  's.call',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Callsign or other ID',
            ],
            'LSB' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'LSB',
                'label'     =>  'LSB',
                'order'     =>  'a',
                'sort'      =>  's.LSB',
                'td_class'  =>  'txt_r',
                'th_class'  =>  '',
                'tooltip'   =>  'Lower sideband offset',
            ],
            'USB' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'USB',
                'label'     =>  'USB',
                'order'     =>  'a',
                'sort'      =>  's.USB',
                'td_class'  =>  'txt_r',
                'th_class'  =>  '',
                'tooltip'   =>  'Upper sideband offset',
            ],
            'sec' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'sec',
                'label'     =>  'Sec',
                'order'     =>  'a',
                'sort'      =>  's.sec',
                'td_class'  =>  'txt_r',
                'th_class'  =>  '',
                'tooltip'   =>  'Cycle time in seconds',
            ],
            'format' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'format',
                'label'     =>  'Fmt',
                'order'     =>  'a',
                'sort'      =>  's.format',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Format',
            ],
            'QTH' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'QTH',
                'label'     =>  '\'Name\' and Location',
                'order'     =>  'a',
                'sort'      =>  's.QTH',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Location',
            ],
            'SP' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'SP',
                'label'     =>  'S/P',
                'order'     =>  'a',
                'sort'      =>  's.SP',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'State / Province / Territory',
            ],
            'ITU' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'ITU',
                'label'     =>  'ITU',
                'order'     =>  'a',
                'sort'      =>  's.ITU',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Country',
            ],
            'region' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'region',
                'label'     =>  '<div>Continent</div>',
                'order'     =>  'a',
                'sort'      =>  's.region',
                'td_class'  =>  '',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  '',
            ],
            'GSQ' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'GSQ',
                'label'     =>  'GSQ',
                'order'     =>  'a',
                'sort'      =>  's.GSQ',
                'td_class'  =>  'txt_r monospace',
                'th_class'  =>  '',
                'tooltip'   =>  'Listener Grid Square',
            ],
            'pwr' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'pwr',
                'label'     =>  'Pwr',
                'order'     =>  'a',
                'sort'      =>  's.pwr',
                'td_class'  =>  'txt_r',
                'th_class'  =>  '',
                'tooltip'   =>  'Power in Watts',
            ],
            'notes' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'notes',
                'label'     =>  'Notes',
                'order'     =>  'a',
                'sort'      =>  's.notes',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Notes about this signal',
            ],
            'heard_in' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'heard_in_html',
                'label'     =>  'Heard In<br /><em>(Daytime Log)</em>',
                'order'     =>  'a',
                'sort'      =>  's.heard_in',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Places where this signal has been reported',
            ],
            'logs' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'logs',
                'label'     =>  'Logs',
                'order'     =>  'a',
                'sort'      =>  's.logs',
                'td_class'  =>  'txt_r',
                'th_class'  =>  '',
                'tooltip'   =>  'Number of times this signal has been logged',
            ],
            'first_heard' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'first_heard',
                'label'     =>  'First Logged',
                'order'     =>  'a',
                'sort'      =>  's.first_heard',
                'td_class'  =>  'text-nowrap txt_r monospace',
                'th_class'  =>  '',
                'tooltip'   =>  'Date on which signal was first logged',
            ],
            'last_heard' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'last_heard',
                'label'     =>  'Last Logged',
                'order'     =>  'a',
                'sort'      =>  's.last_heard',
                'td_class'  =>  'text-nowrap txt_r monospace',
                'th_class'  =>  '',
                'tooltip'   =>  'Date on which signal was last logged',
            ],
            'rangeKm' => [
                'admin'     =>  false,
                'arg'       =>  'range_gsq',
                'field'     =>  'rangeKm',
                'label'     =>  'KM',
                'order'     =>  'a',
                'sort'      =>  'rangeKm',
                'td_class'  =>  'txt_r monospace',
                'th_class'  =>  '',
                'tooltip'   =>  'Distance in kilometers from GSQ',
            ],
            'rangeMi' => [
                'admin'     =>  false,
                'arg'       =>  'range_gsq',
                'field'     =>  'rangeMi',
                'label'     =>  'Miles',
                'order'     =>  'a',
                'sort'      =>  'rangeMi',
                'td_class'  =>  'txt_r monospace',
                'th_class'  =>  '',
                'tooltip'   =>  'Distance in miles from GSQ',
            ],
            'admin' => [
                'admin'     =>  true,
                'arg'       =>  '',
                'field'     =>  'formattedDeleteLink',
                'label'     =>  'Admin',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
        ];
    }
}
