<?php
/**
 * Created by PhpStorm.
 * User: mfrancis
 * Date: 2018-09-03
 * Time: 04:44
 */

namespace App\Columns;

class Signals
{
    public function getColumns()
    {
        return [
            'khz' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'khz',
                'label'     =>  'KHz',
                'order'     =>  'a',
                'sort'      =>  's.khz',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Frequency',
            ],
            'call' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'call',
                'label'     =>  'ID',
                'order'     =>  'a',
                'sort'      =>  's.call',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Callsign or other ID',
            ],
            'lsb' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'lsb',
                'label'     =>  'LSB',
                'order'     =>  'a',
                'sort'      =>  's.lsb',
                'td_class'  =>  'txt_r',
                'th_class'  =>  '',
                'tooltip'   =>  'Lower sideband offset',
            ],
            'usb' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'usb',
                'label'     =>  'USB',
                'order'     =>  'a',
                'sort'      =>  's.usb',
                'td_class'  =>  'txt_r',
                'th_class'  =>  '',
                'tooltip'   =>  'Upper sideband offset',
            ],
            'sec' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'sec',
                'label'     =>  'Sec',
                'order'     =>  'a',
                'sort'      =>  's.sec',
                'td_class'  =>  'txt_r',
                'th_class'  =>  '',
                'tooltip'   =>  'Cycle time in seconds',
            ],
            'format' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'format',
                'label'     =>  'Fmt',
                'order'     =>  'a',
                'sort'      =>  's.format',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Format',
            ],
            'qth' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'qth',
                'label'     =>  '\'Name\' and Location',
                'order'     =>  'a',
                'sort'      =>  's.qth',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Location',
            ],
            'sp' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'sp',
                'label'     =>  'S/P',
                'order'     =>  'a',
                'sort'      =>  's.sp',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'State / Province / Territory',
            ],
            'itu' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'itu',
                'label'     =>  'ITU',
                'order'     =>  'a',
                'sort'      =>  's.itu',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Country',
            ],
            'region' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'formattedRegion',
                'label'     =>  '<div>Continent</div>',
                'order'     =>  'a',
                'sort'      =>  'i.region',
                'td_class'  =>  '',
                'th_class'  =>  'txt_vertical',
                'tooltip'   =>  '',
            ],
            'gsq' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'gsq',
                'label'     =>  'GSQ',
                'order'     =>  'a',
                'sort'      =>  'l.gsq',
                'td_class'  =>  'txt_r monospace',
                'th_class'  =>  '',
                'tooltip'   =>  'Listener Grid Square',
            ],
            'pwr' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'formattedPwr',
                'label'     =>  'Pwr',
                'order'     =>  'a',
                'sort'      =>  's.pwr',
                'td_class'  =>  'txt_r',
                'th_class'  =>  '',
                'tooltip'   =>  'Power in Watts',
            ],
            'notes' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'notes',
                'label'     =>  'Notes',
                'order'     =>  'a',
                'sort'      =>  's.notes',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Notes about this signal',
            ],
            'heardIn' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'heardInHtml',
                'label'     =>  'Heard In<br />(Daytime receptions are bold)',
                'order'     =>  'a',
                'sort'      =>  's.heardIn',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  'Places where this signal has been reported',
            ],
            'logs' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'formattedLogsLink',
                'label'     =>  'Logs',
                'order'     =>  'a',
                'sort'      =>  's.logs',
                'td_class'  =>  'txt_r',
                'th_class'  =>  '',
                'tooltip'   =>  'Number of times this signal has been logged',
            ],
            'firstHeard' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'formattedFirstHeard',
                'label'     =>  'First Logged',
                'order'     =>  'a',
                'sort'      =>  's.firstHeard',
                'td_class'  =>  'text-nowrap txt_r monospace',
                'th_class'  =>  '',
                'tooltip'   =>  'Date on which signal was first logged',
            ],
            'lastHeard' => [
                'admin'     =>  false,
                'arg'       =>  '',
                'field'     =>  'formattedLastHeard',
                'label'     =>  'Last Logged',
                'order'     =>  'a',
                'sort'      =>  's.lastHeard',
                'td_class'  =>  'text-nowrap txt_r monospace',
                'th_class'  =>  '',
                'tooltip'   =>  'Date on which signal was last logged',
            ],
            'admin' => [
                'admin'     =>  true,
                'arg'       =>  '',
                'field'     =>  'formattedDeleteLink',
                'label'     =>  'Admin',
                'order'     =>  '',
                'sort'      =>  '',
                'td_class'  =>  '',
                'th_class'  =>  '',
                'tooltip'   =>  '',
            ],
        ];
    }
}
