<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230827192904 extends AbstractMigration
{
    public function getDescription() : string
    {
        return 'Sync DB schema with application mapping';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE donors CHANGE anonymous anonymous TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE listeners CHANGE active active VARCHAR(1) DEFAULT \'Y\' NOT NULL, CHANGE multi_operator multi_operator VARCHAR(1) NOT NULL, CHANGE primary_QTH primary_QTH VARCHAR(255) NOT NULL, CHANGE wwsu_enable wwsu_enable LONGTEXT NOT NULL, CHANGE wwsu_key wwsu_key VARCHAR(20) NOT NULL, CHANGE wwsu_perm_cycle wwsu_perm_cycle LONGTEXT NOT NULL, CHANGE wwsu_perm_offsets wwsu_perm_offsets LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE log_sessions CHANGE comment comment VARCHAR(255) NOT NULL, CHANGE upload_count upload_count INT UNSIGNED NOT NULL, CHANGE upload_cursor upload_cursor INT UNSIGNED NOT NULL, CHANGE upload_percent upload_percent INT UNSIGNED NOT NULL, CHANGE upload_status upload_status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE stats CHANGE listeners_reu listeners_reu INT UNSIGNED NOT NULL, CHANGE listeners_rna listeners_rna INT UNSIGNED NOT NULL, CHANGE listeners_rww listeners_rww INT UNSIGNED NOT NULL, CHANGE listeners_rww_af listeners_rww_af INT UNSIGNED NOT NULL, CHANGE listeners_rww_an listeners_rww_an INT UNSIGNED NOT NULL, CHANGE listeners_rww_as listeners_rww_as INT UNSIGNED NOT NULL, CHANGE listeners_rww_ca listeners_rww_ca INT UNSIGNED NOT NULL, CHANGE listeners_rww_eu listeners_rww_eu INT UNSIGNED NOT NULL, CHANGE listeners_rww_iw listeners_rww_iw INT UNSIGNED NOT NULL, CHANGE listeners_rww_na listeners_rww_na INT UNSIGNED NOT NULL, CHANGE listeners_rww_oc listeners_rww_oc INT UNSIGNED NOT NULL, CHANGE listeners_rww_sa listeners_rww_sa INT UNSIGNED NOT NULL, CHANGE logs_reu logs_reu INT UNSIGNED NOT NULL, CHANGE logs_rna logs_rna INT UNSIGNED NOT NULL, CHANGE logs_rww logs_rww INT UNSIGNED NOT NULL, CHANGE logs_rww_af logs_rww_af INT UNSIGNED NOT NULL, CHANGE logs_rww_an logs_rww_an INT UNSIGNED NOT NULL, CHANGE logs_rww_as logs_rww_as INT UNSIGNED NOT NULL, CHANGE logs_rww_ca logs_rww_ca INT UNSIGNED NOT NULL, CHANGE logs_rww_eu logs_rww_eu INT UNSIGNED NOT NULL, CHANGE logs_rww_iw logs_rww_iw INT UNSIGNED NOT NULL, CHANGE logs_rww_na logs_rww_na INT UNSIGNED NOT NULL, CHANGE logs_rww_oc logs_rww_oc INT UNSIGNED NOT NULL, CHANGE logs_rww_sa logs_rww_sa INT UNSIGNED NOT NULL, CHANGE signals_reu signals_reu INT UNSIGNED NOT NULL, CHANGE signals_rna signals_rna INT UNSIGNED NOT NULL, CHANGE signals_rna_reu signals_rna_reu INT UNSIGNED NOT NULL, CHANGE signals_rww signals_rww INT UNSIGNED NOT NULL, CHANGE signals_rww_af signals_rww_af INT UNSIGNED NOT NULL, CHANGE signals_rww_an signals_rww_an INT UNSIGNED NOT NULL, CHANGE signals_rww_as signals_rww_as INT UNSIGNED NOT NULL, CHANGE signals_rww_ca signals_rww_ca INT UNSIGNED NOT NULL, CHANGE signals_rww_eu signals_rww_eu INT UNSIGNED NOT NULL, CHANGE signals_rww_iw signals_rww_iw INT UNSIGNED NOT NULL, CHANGE signals_rww_na signals_rww_na INT UNSIGNED NOT NULL, CHANGE signals_rww_oc signals_rww_oc INT UNSIGNED NOT NULL, CHANGE signals_rww_sa signals_rww_sa INT UNSIGNED NOT NULL, CHANGE signals_unlogged signals_unlogged INT UNSIGNED NOT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE donors CHANGE anonymous anonymous TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE listeners CHANGE active active CHAR(1) CHARACTER SET utf8 DEFAULT \'Y\' COLLATE `utf8_general_ci`, CHANGE multi_operator multi_operator CHAR(1) CHARACTER SET utf8 DEFAULT \'N\' NOT NULL COLLATE `utf8_general_ci`, CHANGE primary_QTH primary_QTH CHAR(1) CHARACTER SET utf8 DEFAULT \'N\' NOT NULL COLLATE `utf8_general_ci`, CHANGE wwsu_enable wwsu_enable CHAR(1) CHARACTER SET utf8 DEFAULT \'N\' NOT NULL COLLATE `utf8_general_ci`, CHANGE wwsu_key wwsu_key VARCHAR(20) CHARACTER SET utf8 DEFAULT \'\' NOT NULL COLLATE `utf8_general_ci`, CHANGE wwsu_perm_cycle wwsu_perm_cycle CHAR(1) CHARACTER SET utf8 DEFAULT \'N\' NOT NULL COLLATE `utf8_general_ci`, CHANGE wwsu_perm_offsets wwsu_perm_offsets CHAR(1) CHARACTER SET utf8 DEFAULT \'N\' NOT NULL COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE log_sessions CHANGE comment comment VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, CHANGE upload_count upload_count INT UNSIGNED DEFAULT NULL, CHANGE upload_cursor upload_cursor INT UNSIGNED DEFAULT NULL, CHANGE upload_percent upload_percent TINYINT(1) DEFAULT NULL, CHANGE upload_status upload_status VARCHAR(255) CHARACTER SET utf8 DEFAULT \'Uploaded\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE stats CHANGE listeners_reu listeners_reu INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE listeners_rna listeners_rna INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE listeners_rww listeners_rww INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE listeners_rww_af listeners_rww_af INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE listeners_rww_an listeners_rww_an INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE listeners_rww_as listeners_rww_as INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE listeners_rww_ca listeners_rww_ca INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE listeners_rww_eu listeners_rww_eu INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE listeners_rww_iw listeners_rww_iw INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE listeners_rww_na listeners_rww_na INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE listeners_rww_oc listeners_rww_oc INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE listeners_rww_sa listeners_rww_sa INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE logs_reu logs_reu INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE logs_rna logs_rna INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE logs_rww logs_rww INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE logs_rww_af logs_rww_af INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE logs_rww_an logs_rww_an INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE logs_rww_as logs_rww_as INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE logs_rww_ca logs_rww_ca INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE logs_rww_eu logs_rww_eu INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE logs_rww_iw logs_rww_iw INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE logs_rww_na logs_rww_na INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE logs_rww_oc logs_rww_oc INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE logs_rww_sa logs_rww_sa INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_reu signals_reu INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_rna signals_rna INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_rna_reu signals_rna_reu INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_rww signals_rww INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_rww_af signals_rww_af INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_rww_an signals_rww_an INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_rww_as signals_rww_as INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_rww_ca signals_rww_ca INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_rww_eu signals_rww_eu INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_rww_iw signals_rww_iw INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_rww_na signals_rww_na INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_rww_oc signals_rww_oc INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_rww_sa signals_rww_sa INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE signals_unlogged signals_unlogged INT UNSIGNED DEFAULT 0 NOT NULL');
    }
}
