<?php
namespace App\Controller\Web\Listeners\Export;

use App\Controller\Web\Listeners\Base;
use App\Repository\ListenerRepository;
use App\Repository\TypeRepository;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class Listeners
 * @package App\Controller\Web\Listener\Export
 */
class Signals extends Base
{
    /**
     * @Route(
     *     "/{_locale}/{system}/listeners/{id}/signals/export/csv",
     *     requirements={
     *        "_locale": "de|en|es|fr",
     *        "system": "reu|rna|rww"
     *     },
     *     defaults={"id"=""},
     *     name="listener_signals_export_csv"
     * )
     * @param $_locale
     * @param $system
     * @param $id
     * @param ListenerRepository $listenerRepository
     * @param TypeRepository $typeRepository
     * @return RedirectResponse|Response
     */
    public function csv(
        $_locale,
        $system,
        $id,
        ListenerRepository $listenerRepository,
        TypeRepository $typeRepository
    ) {
        return $this->export($_locale, $system, $id, 'csv', $listenerRepository, $typeRepository);
    }

    /**
     * @Route(
     *     "/{_locale}/{system}/listeners/{id}/signals/export/kml/{type}/{active}",
     *     requirements={
     *        "_locale": "de|en|es|fr",
     *        "system": "reu|rna|rww"
     *     },
     *     defaults={"id"="", "type"="*", "active"="*"},
     *     name="listener_signals_export_kml"
     * )
     * @param $_locale
     * @param $system
     * @param $id
     * @param $type
     * @param $active
     * @param ListenerRepository $listenerRepository
     * @param TypeRepository $typeRepository
     * @return RedirectResponse|Response
     */
    public function kml(
        $_locale,
        $system,
        $id,
        $type,
        $active,
        ListenerRepository $listenerRepository,
        TypeRepository $typeRepository
    ) {
        if (!$listener = $this->getValidReportingListener($id, $listenerRepository)) {
            return $this->redirectToRoute(
                'listeners',
                [ '_locale' => $_locale, 'system' => $system ]
            );
        }
        $filter =                   [];
        if ($active !== '*') {
            $filter['active'] = $active;
        }
        if ($type !== '*') {
            $filter['type'] = explode(',', $type);
        }
        $parameters = [
            'colors' =>             $typeRepository->getMapIconColorForCodes(),
            'description' =>        "Generated by ".strToUpper($system)." on ".date('Y-m-d'),
            'filter' =>             $filter,
            '_locale' =>            $_locale,
            'signals' =>            $listenerRepository->getSignalsForListener($id, $filter),
            'title' =>              strToUpper($system).' stations received by '.$listener->getName(),
            'types' =>              $typeRepository->getAll()
        ];
        $parameters =   array_merge($parameters, $this->parameters);
        $filename =
            "listener_"
            .$id
            ."_signals"
            .($type !== '*' ? "_type_".str_replace(',','_', $type) : '')
            .($active !== '*' ? "_".($active ? "active" : "inactive") : "")
            .".kml";
        $response =     $this->render('listener/export/signals.kml.twig', $parameters);
        $response->headers->set('Content-Disposition',"attachment;filename={$filename}");
        $response->headers->set('Content-Type', 'application/vnd.google-earth.kml+xml');
//        $response->headers->set('Content-Type', 'text/plain');
        return $response;
    }

    /**
     * @Route(
     *     "/{_locale}/{system}/listeners/{id}/signals/export/txt",
     *     requirements={
     *        "_locale": "de|en|es|fr",
     *        "system": "reu|rna|rww"
     *     },
     *     defaults={"id"=""},
     *     name="listener_signals_export_txt"
     * )
     * @param $_locale
     * @param $system
     * @param $id
     * @param ListenerRepository $listenerRepository
     * @param TypeRepository $typeRepository
     * @return RedirectResponse|Response
     */
    public function txt(
        $_locale,
        $system,
        $id,
        ListenerRepository $listenerRepository,
        TypeRepository $typeRepository
    ) {
        return $this->export($_locale, $system, $id, 'txt', $listenerRepository, $typeRepository);
    }

    /**
     * @param $_locale
     * @param $system
     * @param $id
     * @param $mode
     * @param ListenerRepository $listenerRepository
     * @param TypeRepository $typeRepository
     * @return RedirectResponse|Response
     */
    private function export(
        $_locale,
        $system,
        $id,
        $mode,
        ListenerRepository $listenerRepository,
        TypeRepository $typeRepository
    ) {
        if (!$listener = $this->getValidReportingListener($id, $listenerRepository)) {
            return $this->redirectToRoute(
                'listeners',
                [ '_locale' => $_locale, 'system' => $system ]
            );
        }
        $signals = $listenerRepository->getSignalsForListener($id, ['sort' => 'khz']);
        $parameters = [
            '_locale' =>            $_locale,
            'title' =>              strToUpper($system) . ' signals for '.$listener->getName() . " on " . date('Y-m-d'),
            'subtitle' =>           '(' . count($signals) . ' records sorted by Frequency and ID)',
            'system' =>             $system,
            'listener' =>           $listener,
            'signals' =>            $signals,
            'typeRepository' =>     $typeRepository
        ];
        $parameters =   array_merge($parameters, $this->parameters);
        switch ($mode) {
            case 'csv':
                $response = $this->render("listener/export/signals.csv.twig", $parameters);
                break;
            case 'txt':
                $response = $this->render("listener/export/signals.txt.twig", $parameters);
                break;
        }
        $response->headers->set('Content-Type', 'text/plain');
        $response->headers->set('Content-Disposition',"attachment;filename=listener_{$id}_signals.{$mode}");
        return $response;
    }
}
